mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.javagpt.user.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

server:
  port: 8089

wx:
  appId: wxb7ca6048ec426f03
  appSecret: d29708209e6e4707431bbd8cd314396e
  server: http://gfqqgh.natappfree.cc

  # 微信开放平台 appid
  open:
    app_id: wx1292a69b2cd3c5b7
    # 微信开放平台 appsecret
    app_secret: dd776adcd6bb79a9a05a30e3a67ed7b3
    # 微信开放平台重定向url，即扫码登录后回调的后端api，中间的ip地址是内网穿透的
    redirect_url: http://17bbf738.r10.cpolar.top/buildBaseFrame/api/v1/user/wechat/login/wx

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: user-provider
  thymeleaf:
    cache: false #关闭缓存

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    root: debug
