#!/bin/bash

#基础镜像
FROM openjdk:8-jdk-alpine

#作者
MAINTAINER xuwangcheng 2631416434@qq.com

#执行命令，主要用来安装相关的软件
#RUN
#添加文件
ADD back-0.0.1-SNAPSHOT.jar /usr/local
RUN chmod u+x /usr/local/back-0.0.1-SNAPSHOT.jar

#挂载目录到容器
#VOLUME ["/data"]
#环境变量设置
#ENV #开放端口
EXPOSE 8088

#启动时执行的命令
CMD ["/bin/bash"]
ENTRYPOINT ["java","-jar","/usr/local/back-0.0.1-SNAPSHOT.jar"]
