server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  application:
    name: education-platform
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  threads:
    virtual:
      enabled: true
  es:
    host: localhost
    port: 9200
  elasticsearch:
    uris: http://127.0.0.1:9200
    username: elastic
    password: HYnyGbJ7LOXVUN*8XByl
  #  kafka:
  #    bootstrap-servers: 10.51.51.2:9093
  #    producer:
  #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #    consumer:
  #      group-id: my-group # 消费者组 ID
  #      auto-offset-reset: earliest
  #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    compatibility-verifier:
      enabled: false
    sentinel:
      filter:
        # 打开/关闭掉对 Spring MVC 端点的保护
        enabled: true
      transport:
        # 指定控制台的地址
        dashboard: localhost:8080
        # 指定和控制台通信的IP
        # 如不配置，会自动选择一个IP注册
        client-ip: 127.0.0.1
        # 指定和控制台通信的端口，默认值8719
        # 如不设置，会自动从8719开始扫描，依次+1，直到找到未被占用的端口
        port: 8719
        # 心跳发送周期，默认值null
        # 但在SimpleHttpHeartbeatSender会用默认值10秒
        heartbeat- interval-ms: 10000
      eager: true
management:
  endpoints:
    web:
      exposure:
        include: '*' # 开启所有端点

logging:
  level:
    root: info
  structured:
    format:
      console: ecs
  #  file:
  #    name: "logs/education-platform.log"

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis-plus:
  auto-mapping-behavior: full # 自动映射
  map-underscore-to-camel-case: true # 下划线转驼峰
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.javagpt.back.entity #扫描表映射的类，默认是自动加下划线
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  global-config:
    banner: false
    db-config:
      id-type: auto
      column-underline: true
      logic-delete-field: deleteFlag # 指定字段名
      logic-delete-value: 1 # 删除后设置成的值
      logic-not-delete-value: 0 # 未删除的值

mpp:
  entityBasePath: com.javagpt.back.entity

exclude-url:
  ip-limit-urls:
    - /back/pilot/getList

springdoc: # http://localhost:8089/swagger-ui/index.html#/
  api-docs:
    enabled: true # 开启OpenApi接口
    version: OPENAPI_3_1
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启