mybatis-plus:
  auto-mapping-behavior: full # 自动映射
  map-underscore-to-camel-case: true # 下划线转驼峰
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.javagpt.back.entity #扫描表映射的类，默认是自动加下划线
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  global-config:
    banner: false
    db-config:
      id-type: auto
      column-underline: true
      logic-delete-field: deleteFlag # 指定字段名
      logic-delete-value: 1 # 删除后设置成的值
      logic-not-delete-value: 0 # 未删除的值

server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  application:
    name: education-platform
  threads:
    virtual:
      enabled: true
  es:
    host: localhost
    port: 9200

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mpp:
  entityBasePath: com.javagpt.back.entity

logging:
  file:
    name: "logs/education-platform.log"
  level:
    root: info

#对象存储
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tM11FARgMsCGjaYtCQk
  accessKeySecret: g80zES4Xygyrx4stk2XhEYeV0xRSiK
  bucketName: sss970722