#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
#  type-aliases-package: com.javagpt.back.entity
#  configuration:
#    map-underscore-toVO-camel-case: true
#    use-generated-keys: true
#
#server:
#  port: 8088
#
## DataSource Config
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/education?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#  application:
#    name: back-server
#
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#
#mpp:
#  entityBasePath: com.javagpt.back.entity
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.javagpt.back.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

server:
  port: 8088

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.32.191.118:3306/education?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Zxcvbnm1234567890
  application:
    name: back-server
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  kafka:
    bootstrap-servers: 10.51.51.2:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-group # 消费者组 ID
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mpp:
  entityBasePath: com.javagpt.back.entity

logging:
  level:
    root: info
