server:
  port: 8088

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://140.246.54.146:3306/education?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: Zxcvbnm1234567890
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: education-platform

logging:
  level:
    root: info
