server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  application:
    name: education-platform
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
#      sentinel:
#        username: false
  threads:
    virtual:
      enabled: true
  es:
    host: localhost
    port: 9200

logging:
  level:
    root: info
  structured:
    format:
      console: ecs
  #  file:
  #    name: "logs/education-platform.log"
#对象存储
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tM11FARgMsCGjaYtCQk
  accessKeySecret: g80zES4Xygyrx4stk2XhEYeV0xRSiK
  bucketName: sss970722