server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://152.32.191.118:3306/education?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: Zxcvbnm1234567890
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: education-platform
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  threads:
    virtual:
      enabled: true
  es:
    host: localhost
    port: 9200
  elasticsearch:
    uris: http://127.0.0.1:9200
    username: elastic
    password: HYnyGbJ7LOXVUN*8XByl
#  kafka:
#    bootstrap-servers: 10.51.51.2:9093
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: my-group # 消费者组 ID
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging:
  level:
    root: info

springdoc: # http://localhost:8089/swagger-ui/index.html#/
  api-docs:
    enabled: true # 开启OpenApi接口
    version: OPENAPI_3_1
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启

#对象存储
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tM11FARgMsCGjaYtCQk
  accessKeySecret: g80zES4Xygyrx4stk2XhEYeV0xRSiK
  bucketName: sss970722

#nacos:
#  config:
#    server-addr: localhost:8848
#    # 配置所属命名空间的id
#    namespace: ${spring.profiles.active}
#    # 配置所属分组
#    group: icv-archetype
#    # 配置ID
#    data-id: application.yml
#    type: yaml
#    # 开启自动刷新nacos配置
#    auto-refresh: true
#    enable-remote-sync-config: true
#    # 针对配置项同名的情况，是否允许 nacos 的配置覆盖本地的配置
#    remote-first: true
#    bootstrap:
#      enable: true

feign:
  client:
    config:
      default:
        readTimeout: 3000
        connectTimeout: 3000